# Generated by Django 3.0.4 on 2020-03-13 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetingroom', '0003_auto_20200313_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('employee_name', models.CharField(max_length=50)),
                ('employee_designation', models.CharField(max_length=50)),
                ('room_usage', models.BooleanField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='employee_name',
        ),
        migrations.AddField(
            model_name='booking',
            name='emp_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_booking', to='meetingroom.EmployeeDetails'),
        ),
    ]
