# Generated by Django 3.0.4 on 2020-03-14 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetingroom', '0004_auto_20200313_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='emp_id',
            new_name='emp',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='room_id',
            new_name='room',
        ),
    ]
